### PR TITLE
Added support for configuration granularity pipeline as a complement to individual stages. 

### PR DESCRIPTION
**Pull request by draenor**
Used in at least one project. Sample pipeline format

{
    "pipelineName": "contacts",
    "stages": [
    {
        "stageName": "foo",
        "jarId": "solr-writer-0.4.2", 
        "stageClass": "com.findwise.hydra.stage.SetStaticFieldStage",
        "queryOptions": ["touched(extractTitles,true)"],
        "fieldNames": ["source"],
        "fieldValues": ["web"]
    },
    {
        "stageName": "bar",
        "jarId": "solr-writer-0.4.2",
        "stageClass": "com.findwise.hydra.stage.SetStaticFieldStage",
        "queryOptions": ["touched(extractTitles,true)"],
        "fieldNames": ["source"],
        "fieldValues": ["web"]
    }]
}

### CODE REVIEW

**Comment by draenor** [comment]
There's a subsequent (minor) patch on this pull request which fixes some issues and adds a unit test. Github only allows one outstanding pull req though.

**Comment by draenor** [comment]
Probably better to do it all in one sweep

**Comment by jwestberg** [comment]
New commits are added to the pull request, you should be able to just merge to the same branch..

**Comment by draenor** [comment]
It said a pull request was already in place and thereby couldn't add to it. Either way, I've created a new request. 

// Johan Sjöberg

**Pull request closed without merging**
