### PR TITLE
Fixed concurency issue #268 in MemoryCache

### PR DESCRIPTION
**Pull request by staunsbjerg**
- Added synchronization on critical sections
- Added test case for getAndTag in concurrent environment

### CODE REVIEW

**Comment by remen** [comment]
This is one of those cases where the code fix is obviously correct (or at least more correct than what was there before), but where it is very difficult to see whether the test code is correct. My question is, is it worth it? The test is 
- complex,
- tightly coupled to the specific implementation, and
- intrusive (setUnitTestMode).

If you feel strongly that you want to keep it; I'll merge this in. But I vote for removal of the test.

**Comment by staunsbjerg** [comment]
@remen I don't have any strong opinions on keeping the test case or not. I do however feel that intrusive tests with setUnitTestMode is often the best way to go about injecting mocks - else you can end up in constructor overloading-hell.I.e: the code becomes transparent and testable.

I don't think we can make an async test case simplified. So it is up to you guys

**Comment by remen** [comment]
I agree in that I don't think the async test case can be simplified either; and since I don't think it adds enough value in comparison to its complexity, I'll remove it. Thanks for feedback and contribution!

**Comment by remen** [comment]
Manually merged in commit 4dcc1aefa76a39a0e4b985496988caec17daf651

**Comment by remen** [comment]
By the way, I've been down this road before: https://github.com/remen/fork_break, but I've since reached the conclusion that it's not worth the effort. For Java, this seems to be a good lib: http://www.cs.umd.edu/projects/PL/multithreadedtc/overview.html

**Pull request closed without merging**
