### PR TITLE
Added rest endpoints for stage groups

### PR DESCRIPTION
**Pull request by jensbengtsson**
As suggested in https://github.com/Findwise/Hydra/issues/129 I have added end points for listing stage groups as well as adding stages to a named stage group. 

I don't know why the diffs are messed up, showing every line changed. :/

### CODE REVIEW

**Comment by jensbengtsson** [comment]
https://github.com/Findwise/Hydra/pull/138/files?w=1

Show's without white space changes

**Comment by laserval** [comment]
Good stuff! Could you add a short description to the README.md about the new endpoints?

**Comment by jensbengtsson** [comment]
Sure, will do it later and add the commit.

**Comment by laserval** [comment]
Something is messing up the formatting in README.md, could you put the same formatting around the stagegroups response as for the other stuff? I think it's three backticks.

**Comment by laserval** [comment]
The reason for the diff showing every line as changed is that all Unix line endings have been replaced with Windows line endings, so every line is one character longer.

In general Hydra uses only Unix line endings, so if you encounter the same behavior from diff have a look at the line endings.

**Comment by jensbengtsson** [comment]
Netbeans didn't show all lines changed when I diffed in it before commit. Neither did my git shell. So don't know why it ended up that way in the end.

**Pull request merged**
